### ISSUE TITLE
Cache opcional para nodos

### ISSUE THREAD

**Issue by leandro-gomez** [datosgobar/portal-andino#116]
Luego de #112, ver de implementar una cache opcional para los nodos que permita mejorar la usabilidad de la aplicacion.
~La misma debe ser compatible con lo descripto en https://github.com/datosgobar/portal-andino-theme/issues/245~

La misma debe permitir estos caminos:

1. Andino sin caché: Lo que hace Andino 2.4.5 (sólo tiene la configuración recomendada por CKAN).
2. Caché básica: Lo que estamos desarrollando en los issues de Github datosgobar/portal-andino: Issue #136 y datosgobar/portal-andino-theme: Issue #245, con la salvedad de que el hook de portal-andino-theme tiene que configurarse solo durante la instalación/actualización de Andino (y los demás comentarios de la tarjeta relacionados al tamaño de la cache). Se habilita con un parámetro durante la instalación/actualización de Andino.
3. Caché avanzada: El usuario instala andino "a la" (1), pero le agrega una caché adelante, en otro servidor. La implementación de esa caché puede ser algo custom que hace el equipo del nodo, o una implementación que debemos tener documentada (basada en la "Caché básica" de Andino). En este escenario, el usuario tiene que configurar el hook del plugin de Andino a mano. 

Las tareas a realizar para avanzar con este requerimiento son:

La instalación y actualización de Andino debe poder recibir un parámetro opcional que si fue provisto permitirá:

* [x] Agregar a _nginx_ la capacidad de invalidar su caché mediante una llamada HTTP (implementar feature agregado en #136).
* [x] Agregar a andino la capacidad de llamar a una url cuando la cache deba ser invalidada (ver https://github.com/datosgobar/portal-andino-theme/issues/245)
* [x] El script de instalacion debe configurar la integracion entre los puntos 1 y 2 automaticamente (ver #138)
* [x] Documentar como realizar el punto 3 (#139)
* [x] Estimar un tamaño en MB de caché recomendado (datosgobar/portal-base#57)
* [x] Configurar la caché de _nginx_ de forma tal en que *extienda* su duración a 4 horas. (#140)
* [x] Escribir documentación para configurar un frontend server con caché basado en openresty _idéntico_ a lo que provee Andino por default, pero en otro server y que use como backend a Andino. Esta documentación será usada por el equipo de infraestructura del Ministerio (u otros miembros de la APN) para configurar su instancia (#144).
