### ISSUE TITLE
Utilización de certificados SSL en Andino

### ISSUE THREAD

**Issue by chdigiorno** [datosgobar/portal-andino#182]
- [x] [Generar los archivos de configuración de Andino con SSL](https://github.com/datosgobar/portal-base/issues/68)
- [x] [Volumen en el contenedor nginx](https://github.com/datosgobar/portal-base/issues/69)
- [x] [Copiado de los archivos del certificado SSL al contenedor nginx](https://github.com/datosgobar/portal-andino/issues/176)
- [x] [Soporte para selección del archivo de configuración de nginx durante la actualización de andino](https://github.com/datosgobar/portal-andino/issues/178)
- [x] [Lógica de selección del archivo de configuración del contenedor nginx](https://github.com/datosgobar/portal-andino/issues/177)
- [x] [Configuración de compose para soporte SSL](https://github.com/datosgobar/portal-andino/issues/179)
- [x] [Actualizaciones a documentación para configuración de SSL](https://github.com/datosgobar/portal-andino/issues/181)
- [x] [Tests de instalación de andino con SSL](https://github.com/datosgobar/portal-andino/issues/180)
