### ISSUE TITLE
Configurar continuous delivery

### ISSUE THREAD

**Issue by poligarcia** [datosgobar/portal-andino#83]
Modificar el script de travis para que:

1. Los commits a un branch nuevo llamado `development` deben:
   1. Buildear una imagen de docker llamada `development`.
   1. Disparar un deploy al ambiente de `dev-andino` de la imagen `development`.
1. Los commits a `master` deben:
   1. Buildear una imagen de docker llamada `staging`.
   1. Disparar un deploy al ambiente de `staging-andino` de la imagen `staging`.
1. Los tags en github deben disparar el proceso de build de las imágenes de docker `latest` y la que lleva el nombre del tag.

Además:
1. El branch `master` debe estar protegido contra commits accidentales por parte del equipo.
1. Los MR deben realizarse contra el branch `development`.
1. Pensar si este proceso debe dispararse cuando se modifica portal-andino y/o portal-andino-theme

## Roadmap:
- [x] #89 Migrar los scripts de instalacion
- [x] #92  Parametrizar la imagen de andino segun una variable al momento del install/update
- [x] #94  Configurar el CD de dev
- [ ] #96 Configurar CD en staging
